# --- !Ups

CREATE TABLE USERS(
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FORENAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    TELEPHONE VARCHAR(15)
);

# --- !Downs
DROP TABLE USERS;